# Update fastlane automatically
update_fastlane

default_platform(:android)

platform :android do
  desc "Build android aab and apk"
  lane :build_android do |options|
    sh "./flutter_test.sh"
    # Build AAB
    sh "./flutter_build.sh --clean"
    # Build APK
    sh "./flutter_build.sh --apk"
  end
end